%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/annielane/Documents/Fall2015/EC500Project/ThyroidData.xlsx
%    Worksheet: all_data
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/11/18 22:29:07

%% Import the data
[~, ~, raw] = xlsread('/Users/annielane/Documents/Fall2015/EC500Project/ThyroidData.xlsx','all_data');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
Thyroid_Features = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw R;

%% Import the data
allbp_labels = xlsread('/Users/annielane/Documents/Fall2015/EC500Project/ThyroidData.xlsx','allbp_labels');

%% Clear temporary variables
clearvars raw;

%% Import the data
allhyper_labels = xlsread('/Users/annielane/Documents/Fall2015/EC500Project/ThyroidData.xlsx','allhyper_labels');

%% Clear temporary variables
clearvars raw;

%% Import the data
allhypo_labels = xlsread('/Users/annielane/Documents/Fall2015/EC500Project/ThyroidData.xlsx','allhypo_labels');

%% Clear temporary variables
clearvars raw;

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/annielane/Documents/Fall2015/EC500Project/ThyroidData.xlsx
%    Worksheet: allrep_labels
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/11/18 22:30:43

%% Import the data
allrep_labels = xlsread('/Users/annielane/Documents/Fall2015/EC500Project/ThyroidData.xlsx','allrep_labels');

%% Clear temporary variables
clearvars raw;

%% Import the data
patient_IDs = xlsread('/Users/annielane/Documents/Fall2015/EC500Project/ThyroidData.xlsx','patient_IDs');

%% Clear temporary variables
clearvars raw;


%% Save the result
save('all_thyroid.mat','allbp_labels','allhyper_labels','allhypo_labels','allrep_labels','Thyroid_Features','patient_IDs');
